[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"


[workspace]
members = ["programs/fluster_trading"]

[features]
seeds = false
skip-lint = false

[programs.localnet]
fluster_trading = "4AHGtdLDrWNPfVaDZD5N8JD2CPFRAZnKdPHtaEohfg9W"

[programs.devnet]
fluster_trading = "4AHGtdLDrWNPfVaDZD5N8JD2CPFRAZnKdPHtaEohfg9W"


[registry]
url = "https://github.com/danielbui12/fluster_trading"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -r tsconfig-paths/register -t 1000000 tests/**/*.test.ts"
node = "yarn ts-node -r tsconfig-paths/register tests/nodes/index.ts" 
exec = "yarn ts-node -r tsconfig-paths/register clients/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# Metaplex
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# Chainlink SOL/USD
[[test.validator.clone]]
address = "CH31Xns5z3M1cTAbKW34jcxPPciazARpijcHj9rxtemt"

# Chainlink program
[[test.validator.clone]]
address = "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny"
[[test.validator.clone]]
address = "cjg3oHmg9uuPsP8D6g29NWvhySJkdYdAo9D25PRbKXJ"


# Pyth SOL/USD
[[test.validator.clone]]
address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"

# Clockwork Network
[[test.validator.clone]]
address = "F8dKseqmBoAkHx3c58Lmb9TgJv5qeTf3BbtZZSEzYvUa"

# Clockwork Thread v2
[[test.validator.clone]]
address = "CLoCKyJ6DXBJqqu2VWx9RLbgnwwR6BMHHuyasVmfMzBh"

# # Raydium AMM
# [[test.validator.clone]]
# address = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"